### ISSUE TITLE
Would like to use in production

### ISSUE THREAD

**Issue by larsacus** [luisespinoza/LEColorPicker#2]
I would like to use this in another [open source component I'm working on](https://github.com/larsacus/TOLDeveloperAds). I really don't feel that the version that is available from CocoaPods is ready for production (lots of extra `NSLog`s, dictionary for colors, etc.

I was looking at forking and making some changes but noticed you have been doing some more recent development in other branches but couldn't necessarily tell where I might could help out. Is there any way I could help out in my free time in getting this into a state that I could use it in a production open-source component?

I was also looking into [panicinc/ColorArt](https://github.com/panicinc/ColorArt), but the output from their algorithm doesn't seem to do as well for the specific use-case of images that I'm looking to process (app store icons).

Some changes I was hoping to make to make at the very least for my specific application:
1. Remove or conditionalize `NSLog` statements
2. Convert color results into a struct or class so code completion can be used

This is just a courtesy question asking what your plans are for this project so that when I do fork it for my own use that I don't squash any plans you may have had for the final architecture of this so that I might merge my changes back upstream.

**Comment by luisespinoza** [comment]
Hi Lars,

Plans: In development branch I made some architectural changes, because I want an architecture that provides some flexibility to test different algorithms for the color's computation. From that branch I made another branch "developGPUQuantization" that I'm using to trying to speed up the color's computation, that is currently very slow. So my primary objective for now is to speed up the computation. Then, my objective will be to make better the computed colors, maybe more close to iTunes output.

Your changes: I think that are great changes, well is my first popular project, so I missed that details. I think that they will not conflict with my current architecture (logically speaking) . However, due the change of architecture, if we put this changes in master, in the merge with develop, we can loose some work. 

How you can contribute: Well, you are the first person with that intention, I don't know what is the usual way, but i think in some options, and you can choose whatever you want.

1.- You can submit a pull request to master with your changes, and I will port this work to the others branches.
2.- I can add you as contributor, so you will be free to make changes anytime you want.
3.- I can make the changes myself (this is the most boring option).

Thank you so much for your interest and contribution. Feel free to contact me anytime you want. I'll be waiting for your reply.

**Comment by larsacus** [comment]
We can do a combination of option 2 & 1 since you've already added me as a contributor. I'll look over your dev branches and see if I can start from there.

**Comment by luisespinoza** [comment]
OK, no problem.
